-- OBSOLETO: este arquivo representava a fase inicial dos pedidos com Stripe.
-- Nao execute este SQL.
--
-- Ele foi neutralizado porque continha DDL destrutiva (`DROP TABLE ... CASCADE`)
-- e ja nao representa o estado atual do projeto.
--
-- Fonte de verdade atual:
-- 1. Supabase migrations em `supabase/migrations/`
-- 2. Cutover AbacatePay em `src/sql/abacatepay_cutover.sql`
